[package]
name = "puzzle-core"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
kurbo = { version = "0.13", features = ["serde"] }
rand = { version = "0.10", default-features = false }
rand_chacha = "0.10"
linesweeper = "0.3"

[dev-dependencies]
serde_json = "1.0"
